name = "packwiz-lt-aoc-aeronautics"
author = "tsandrini"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05aad4e38dd7278f31f71c6f25cf806468d767670d8a1c1cffecc7396e2afe35"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
