name = "packwiz-lt-aoc-aeronautics"
author = "tsandrini"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29173cbf0f54c71d568e3b500c8d972501dadabfaca293a81a1e1e693245ee01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
